version: "3.8"

services:
  db:
    container_name: ${DB_CONNECTION}
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: GMT-4
      PGTZ: GMT-4
    volumes:
      - ./PostgeSQL/data:/var/lib/postgresql/data
      - ./Matcha_Data/matcha_init.sql:/docker-entrypoint-initdb.d/matcha_init.sql
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped
    networks:
      - ft_matcha

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_USERNAME}@mail.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - ft_matcha

networks:
  ft_matcha:
    driver: bridge
