version: "3.8"

services:
  db:
    container_name: ${DB_CONNECTION}
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: GMT-4
      PGTZ: GMT-4
    volumes:
      - ./PostgeSQL/data:/var/lib/postgresql/data
      - ./Matcha_Data/matcha_init.sql:/docker-entrypoint-initdb.d/matcha_init.sql
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped
    networks:
      - ft_matcha

  frontend:
    container_name: frontend
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
    - 8080:8080
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - ft_matcha
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - backend

networks:
  ft_matcha:
    driver: bridge
