version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:alpine
    env_file:
      - ./.env
    volumes:
      - ./PostgeSQL/data:/var/lib/postgresql/data
      - ./data/matcha_init.sql:/docker-entrypoint-initdb.d/matcha_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ft_matcha
        
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - ft_matcha

networks:
  ft_matcha:
    driver: bridge
