version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:alpine
    env_file:
      - ./.env
    volumes:
      - ./PostgeSQL/data:/var/lib/postgresql/data
      - ./data/matcha_init.sql:/docker-entrypoint-initdb.d/matcha_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ft_matcha
        
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - ft_matcha

  vueapp:
    container_name: vueapp
    build:
      dockerfile: ./vueapp/Dockerfile
    env_file:
    - ./.env
    ports:
      - "8080:8080"
      - "24678:24678"
    volumes:
      - ./vueapp:/usr/src/app
    networks:
      - ft_matcha
    restart: unless-stopped
    depends_on:
      - aspnetapp

  aspnetapp:
    container_name: aspnetapp
    build:
      context: aspnetapp
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5001:5001"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - ft_matcha

networks:
  ft_matcha:
    driver: bridge
