services:
  
  backend:
    build:
      context: ./aspnetapp
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - ft_matcha
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build:
      context: ./vueapp
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ft_matcha
    depends_on:
      - backend
      
  db:
    container_name: postgres
    image: postgres:16
    env_file:
      - ./.env
    volumes:
      - ./PostgeSQL/data:/var/lib/postgresql/data
      - ./data/matcha_init.sql:/docker-entrypoint-initdb.d/matcha_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ft_matcha
        
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - ft_matcha

networks:
  ft_matcha:
    driver: bridge
